  services: 
    backend:
      build:
        context: ./back-end
      ports:
        - "5002:5002"
      networks:
        - training-mern-network
      

    frontend: 
      build: 
        context: ./front-end
      ports:
        - "8002:80"
      networks:
      - training-mern-network # <--- Make sure this is here!

    
    mongo:
      image: mongo:latest
      ports:
        - "27019:27017"
      networks:
        - training-mern-network
      
  networks:
    training-mern-network:
      driver: bridge
